"""empty message

Revision ID: 8cdc50bf0c4d
Revises: 3494ae6e4039
Create Date: 2024-01-10 07:14:56.355812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cdc50bf0c4d'
down_revision = '3494ae6e4039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning',
    sa.Column('associate_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('skill_name', sa.String(length=255), nullable=False),
    sa.Column('learning_resource', sa.String(length=255), nullable=False),
    sa.Column('resource_link', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='cdp_tables'
    )
    with op.batch_alter_table('learning', schema='cdp_tables') as batch_op:
        batch_op.create_index('idx_learning_associate_id', ['associate_id'], unique=False)
        batch_op.create_index('idx_learning_email', ['email'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    with op.batch_alter_table('learning', schema='cdp_tables') as batch_op:
        batch_op.drop_index('idx_learning_email')
        batch_op.drop_index('idx_learning_associate_id')

    op.drop_table('learning', schema='cdp_tables')
    # ### end Alembic commands ###
