"""Creating student table

Revision ID: 3494ae6e4039
Revises:
Create Date: 2023-12-05 19:50:47.746505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3494ae6e4039'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning',
    sa.Column('associate_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('skill_name', sa.String(length=255), nullable=False),
    sa.Column('learning_resource', sa.String(length=255), nullable=False),
    sa.Column('resource_link', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),

    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Student')
    # ### end Alembic commands ###
