"""added email field

Revision ID: c34112c3890f
Revises: ca3c687728bb
Create Date: 2023-11-03 16:57:01.256156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c34112c3890f'
down_revision = 'ca3c687728bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Student_timetable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Student_timetable', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
