"""empty message

Revision ID: ca3c687728bb
Revises: 
Create Date: 2023-11-03 15:32:52.711840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3c687728bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Student_timetable',
    sa.Column('initial_percentage', sa.Integer(), nullable=True),
    sa.Column('final_percentage', sa.Integer(), nullable=True),
    sa.Column('threshold_amount', sa.Float(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('distribution_percentage', sa.Integer(), nullable=False),
    sa.Column('base_amount', sa.Float(), nullable=False),
    sa.Column('allocation_date', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Student_timetable')
    # ### end Alembic commands ###
