from week11_pytest_learning.myapp.code1_addition import add
from week11_pytest_learning.myapp.code2_mathfunctions import Algebra, Geometry
from week11_pytest_learning.myapp.code3_age_raise_error import verify_age